### ISSUE TITLE
add basic description

### ISSUE THREAD

**Issue by hellotimi** [emipa606/RelevantStatsInDescription#1]
Hi, I have a requirement. Can Relevant Stats In Description add basic description information for all information card labels？
![NAPLJQ6CO98202JFTGO](https://user-images.githubusercontent.com/8617302/212022640-db51159a-f239-4de1-aabb-0e21230bedde.png)
like this

**Comment by emipa606** [comment]
Sorry, I am trying to keep this mod as simple as possible so modifying the infocards will not be added to the mod.
